name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit and Push changes
      run: |
        git config user.name "llksis"
        git config user.email "qiy319huang@gmail.com"
        git add .
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        # ✅ 解决方案：在推送前，先用 rebase 模式拉取云端的最新改动
        git pull --rebase
        git push